### ISSUE TITLE
Apert not yet responding to OSC or showing control html page

### ISSUE THREAD

**Issue by mattHorrigan** [d0kt0r0/apert#4]
Hello!  I've begun the process of getting apert working on my machine.  Installed the dependencies using `npm`, started up apert.js in node with `--password` set to `testpass`, navigated my web browser to `localhost:8000`, all good thus far, find the html generated by default.js happily waiting there, and when i click the "simple test tone" button a simple test tone sounds.

But, when i go into Max/MSP and use it to send the message `/refresh testpass` over UDP to `localhost` port `8000`, no action in my web browser.  Same when I send the message `/all testpass simple` which i gather should cause the test tone to play.

I also get an error when navigating to `localhost:8080/control`, which i take to mean that apert is not successfully serving that file.

Am i doing something wrong?  Have perused the documentation pretty exhaustively.

**Comment by dktr0** [comment]
Just checked on in this. There was indeed some "bit rot" due to breaking changes in the node ws library. I've just pushed a commit that should bring things back into working order so if you pull the new commit things should work better. (Just to note, since you don't mention it in your post, you need to use the --osc-port option (see node apert.js --help) if you want apert to listen for local OSC, and the "simple" function expects two arguments for frequency and amplitude so: /all password simple 440 0.1).

**Comment by mattHorrigan** [comment]
That fixed it!  Thanks a lot!  Apert is now playing `simple` test tones triggered remotely over OSC.

And yes, I had also neglected to set the `--osc-port` option, so this is why i wasn't getting any feedback from the command line either.  I had been confused by the `listening on port 8000` feedback i'd seen on the command line when starting apert, but realize now this refers to the TCP port used to serve the javascript rather than the UDP port on which apert listens.
